apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-web
  namespace: test
spec:
  replicas: 1
    selector:
      matchLabels:
        app: debug-web
  template:
    metadata:
      labels:
        app: debug-web
    spec:
      restartPolicy: Always
      containers:
        - name: debug-web
          image: donscoco/debugweb:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30080
          env:
            - name: TEST_ENV
              value: "test-env-val"
          volumeMounts:
            - name: nginx-val
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nginx-val
          hostPath:
            path: /usr/share/nginx/html





