apiVersion: v1
kind: Service
metadata:
  name: debug-web          # 修改为 项目的名字
  namespace: test            # 修改为项目的组
spec:
  selector:
    app: debug-web      # 找对应的 pod来 作为 endpoints
  type:  NodePort         # ClusterIP 只能集群访问，NodePort 能让外网访问
  ports:
    - name: httpname          # 这组规则的名字
      protocol: TCP
      nodePort: 30010         # 这个是宿主机上的端口
      port: 30010                # 这个是svc的端口
      targetPort:  30010        # 这个指向deploy的端口，和deploy配置要一样
